/*------------------------------------------------------------------------------
  	$File:			HW_SYS.c
  	$Module:		System wide hardware utilities
  	$Prefix:  	HW
  	$Language:	ANSI C
 
  	$Description:
  	$Notes:
  
  	$Author:	KGANS, 2009-March-24
  	--------------------------------------------------------------------------
  	$Copyright (c) 2009 J.S. Foster Corporation 	All Rights Reserved
  	--------------------------------------------------------------------------
  	$End
  ----------------------------------------------------------------------------*/

#define cMEM_USERCLASS_ID_HW_SYS_c

/*------------------------------------------------------------------------------
							------ I N C L U D E   F I L E S ------
  ------------------------------------------------------------------------------
 */
#include "GLB.h"
#include "HW_Def.h"
//#include "HW_Sys.h"

/*------------------------------------------------------------------------------
							----- M A C R O   D E F I N I T I O N S -----
  ------------------------------------------------------------------------------
 */

/*------------------------------------------------------------------------------
							----- D E F I N I T I O N S -----
  ------------------------------------------------------------------------------
 */

/*------------------------------------------------------------------------------
							----- C O N S T A N T S -----
  ------------------------------------------------------------------------------
 */

/*------------------------------------------------------------------------------
							----- L O C A L   T Y P E S -----
  ------------------------------------------------------------------------------
 */

/*------------------------------------------------------------------------------
							----- L O C A L   F U N C T I O N   P R O T O T Y P E S -----
  ------------------------------------------------------------------------------
 */

/*------------------------------------------------------------------------------
							----- L O C A L   V A R I A B L E S -----
  ------------------------------------------------------------------------------
 */

/*------------------------------------------------------------------------------
							----- G L O B A L   V A R I A B L E S -----
  ------------------------------------------------------------------------------
 */

/*------------------------------------------------------------------------------
							----- L O C A L   F U N C T I O N S -----
  ------------------------------------------------------------------------------
 */

/*------------------------------------------------------------------------------
							----- G L O B A L   F U N C T I O N S -----
  ------------------------------------------------------------------------------
 */

/*------------------------------------------------------------------------------
	$Function: 		HW_SYS_InlineDelay_10us
	$Description: Accepts an argument which is intended as a multiplier for
									a 10us delay
	$Inputs:			args: u32	lwMultiplier
	$Outputs:			return: none
	$CAUTION:			This function does not gaurantee an exact value of the 
								delay resulting from its execution, only that the delay will
								*not be less than* [(10us) * (wlMultiplier)]
	$End
*/
void HW_SYS_InlineDelay_10us( u32 lwMultiplier )
{
	/* each of the following definitions should be verified using an 
			oscilloscope or through a careful count of the delay loop cycles (e.g.
			through examination of the assembler code generated by the compiler) 
	*/
	#if cHW_CLK == cHW_CLK_TEMP_JUNK1
	#define cHW_SYS_InlineDelay_10us (5)
	#elif cHW_CLK == cHW_CLK_TEMP_JUNK2
	#define cHW_SYS_InlineDelay_10us (10)
	#else
	#error "clock rate not supported by HW_SYS_InlineDelay_10us()"
	#endif

	u32	lwDelayCycles,
					lwDelayIterations;

	for( lwDelayIterations = lwMultiplier; 
				((lwDelayIterations) != (0));
				lwDelayIterations--	)
	{
			/* test LED on */
			/* execute delay loop for 10 us 
			*/
			for( lwDelayCycles = cHW_SYS_InlineDelay_10us; 
					(lwDelayCycles); 
					lwDelayCycles-- );
			/* test LED off */
	}		
}

#undef cMEM_USERCLASS_ID_HW_SYS_c


